# Generated by Django 4.0.4 on 2022-04-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_gender_profile_nation_profile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='othernames',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
