# Generated by Django 4.0.4 on 2022-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_othernames_profile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Not Updated', max_length=255, null=True),
        ),
    ]
