# Generated by Django 4.0.4 on 2022-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appstatus',
            field=models.CharField(default='Not Updated', max_length=20, null=True),
        ),
    ]
