# Generated by Django 4.0.4 on 2022-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_appstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appstatus',
            field=models.CharField(default='Update', max_length=20, null=True),
        ),
    ]
