# Generated by Django 4.0.4 on 2022-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_appstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nation',
            field=models.CharField(blank=True, choices=[('Nigeria', 'Nigeria'), ('Cameroon', 'Cameroon'), ('Ghana', 'Ghana')], max_length=10, null=True),
        ),
    ]
