# Generated by Django 4.0.4 on 2022-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_education_reference_alter_profile_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('Tertiary Institution', 'Tertiary Institution'), ('Secondary School', 'Secondary School')], max_length=60, null=True),
        ),
    ]
