# Generated by Django 4.0.4 on 2022-05-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_education_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='university',
            new_name='instition',
        ),
    ]
