# Generated by Django 4.0.4 on 2022-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_university_education_instition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='letter',
        ),
        migrations.AddField(
            model_name='education',
            name='refphone',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='refaddress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
