# Generated by Django 4.0.4 on 2022-05-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_education_letter_education_refphone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='refaddress',
            new_name='matnumber',
        ),
    ]
