# Generated by Django 4.0.4 on 2022-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_refaddress_education_matnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='refphone',
            field=models.IntegerField(null=True),
        ),
    ]
