# Generated by Django 4.0.4 on 2022-05-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_education_refphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilestatus',
            field=models.CharField(default='Update', max_length=30, null=True),
        ),
    ]
