# Generated by Django 4.0.4 on 2022-05-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_submitedapps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Tertiary Institution', 'Tertiary Institution'), ('Secondary School', 'Secondary School')], max_length=60, null=True),
        ),
    ]
