# Generated by Django 4.0.4 on 2022-05-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_education_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitedapps',
            name='submited',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
