# Generated by Django 4.0.4 on 2022-05-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_submitedapps_submited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitedapps',
            old_name='submited',
            new_name='confirm',
        ),
    ]
