# Generated by Django 4.0.4 on 2022-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_submitedapps_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
