# Generated by Django 4.0.4 on 2022-05-05 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0028_alter_education_qualification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitedApps',
            new_name='submited_apps',
        ),
    ]
