# Generated by Django 4.0.4 on 2022-05-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_submited_apps_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited_apps',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
