# Generated by Django 4.0.4 on 2022-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_submited_apps_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nation',
            field=models.CharField(blank=True, choices=[('Benin Republic', 'Benin Republic'), ('Burkina Faso', 'Burkina Faso'), ('Cape Verde', 'Cape Verde'), ("Cote D'Ivoire", "Cote D'Ivoire"), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Liberia', 'Liberia'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Senegal', 'Senegal'), ('Sierra Leone', 'Sierra Leone'), ('Togo', 'Togo')], max_length=20, null=True),
        ),
    ]
