# Generated by Django 4.0.4 on 2022-05-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_rename_submited_apps_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
