# Generated by Django 4.0.4 on 2022-05-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank',
            field=models.CharField(blank=True, choices=[('UBA Bank', 'UBA Bank'), ('ZENITH BANK', 'ZENITH BANK'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('FBNBank Gambia Ltd', 'FBNBank Gambia Ltd'), ('Ecobank', 'Ecobank'), ('Access Bank', 'Access Bank'), ('GTBank', 'GTBank')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nation',
            field=models.CharField(blank=True, choices=[('Benin Republic', 'Benin Republic'), ('Burkina Faso', 'Burkina Faso'), ('Cape Verde', 'Cape Verde'), ("Cote D'Ivoire", "Cote D'Ivoire"), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Liberia', 'Liberia'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Senegal', 'Senegal'), ('Sierra Leone', 'Sierra Leone'), ('Togo', 'Togo')], max_length=255, null=True),
        ),
    ]
