# Generated by Django 4.0.4 on 2022-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_bankdetails_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('Secondary School', 'Secondary School'), ('Undergraduate', 'Undergraduate'), ('Post Graduate', 'Post Graduate')], default=None, max_length=60, null=True),
        ),
    ]
