# Generated by Django 4.0.4 on 2022-05-20 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_scholarship_alter_education_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='category',
            field=models.CharField(choices=[('Secondary School', 'Secondary School'), ('Undergraduate', 'Undergraduate'), ('Post Graduate', 'Post Graduate')], default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitted',
            name='approved',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
