# Generated by Django 3.2.13 on 2022-05-24 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='description',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='fee',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
    ]
