# Generated by Django 3.2.13 on 2022-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20220524_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='instition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='othernames',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
