# Generated by Django 3.2.13 on 2022-05-31 21:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='refphone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
