# Generated by Django 3.2.13 on 2022-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_education_refphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
